spring:
  datasource:
    url: jdbc:postgresql://192.168.1.1:5432/pejt_files
    username: postgres
    password: 1234
  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 1280KB
      max-request-size: 1280KB
      enabled: true
app:
  document-root: src/main/resources/temp
server:
  port: 8085
interceptor:
  kafka:
    bootstrap: "192.168.1.1:9092"
    topic: "url"